# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='body',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=250, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='tuijian',
            field=models.BooleanField(verbose_name='是否推荐'),
        ),
    ]
