# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0002_auto_20161108_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(blank=True, upload_to='artical/%Y/%m/%d'),
        ),
    ]
